# Generated by Django 3.2.25 on 2025-06-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibriApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('Fiction', 'Fiction'), ('Thriller', 'Thriller'), ('History', 'History'), ('Science', 'Science')], max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(upload_to='ebook/'),
        ),
    ]
