# Generated by Django 3.2.25 on 2025-06-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibriApp', '0003_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('Fiction', 'Fiction'), ('Thriller', 'Thriller'), ('Mythology', 'Mythology'), ('Comics', 'Comics')], max_length=100),
        ),
    ]
